### ISSUE TITLE
пофиксить баг с парами из будущего

### ISSUE THREAD

**Issue by w0rng** [mysibsau/backend#38]
у заочников есть пары, которые отображаются сейчас, но должны начаться, например, через месяц (у модели пары на палладе есть поле с датой начала пар)

**Comment by kiri11-mi1** [comment]
![image](https://user-images.githubusercontent.com/47475094/116431847-58885580-a872-11eb-92ec-fd59710d8f5f.png)
в файле api_parsers.py нашёл этот код, я так полагаю это тут мне надо проверять расписание?
и хотел узнать как называется поле в котором хранится время начала пар?

**Comment by w0rng** [comment]
api_pallada вообще не трогай!
тебе надо поправить метод `load_timtable_group_with_parsers` в `apps/timetable/services/setters.py`.

Как поле называется - хз. Тебе надо дернуть метод `fields_get` из вузовского апи, он тебе все расскажет
вот [дока](https://www.odoo.com/documentation/14.0/webservices/odoo.html)

**Comment by w0rng** [comment]
Лучше всего добавить в модельку поле даты, а при сериализации выбирать нужные даты
